[package]
name = "vira-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift = "0.101.5"
cranelift-jit = "0.101.5"
cranelift-module = "0.101.5"
cranelift-native = "0.101.5"
cranelift-object = "0.101.5"
target-lexicon = "0.12.14"
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
